Repository RedisAI/VectorSimilarity, pull requests merged in 2022-08, with the labels that each got.

#191 Add google benchmark to grafana from CI
  .circleci/config.yml
  .github/workflows/perf.yml
  Makefile
  src/VecSim/algorithms/brute_force/brute_force.cpp
  src/VecSim/algorithms/brute_force/brute_force.h
  tests/benchmark/CMakeLists.txt
  tests/benchmark/bm_basics.cpp
  tests/benchmark/bm_batch_iterator.cpp
  tests/benchmark/bm_updated_index.cpp
  tests/benchmark/bm_utils.cpp
  tests/benchmark/bm_utils.h
  tests/benchmark/data/hnsw_indices.txt
  tests/unit/test_bruteforce.cpp
  tox.ini
Labels: run-micro-benchmarks

#178 update brute_force delete algorithm to avoid re-using ids
  src/VecSim/algorithms/brute_force/bf_batch_iterator.cpp
  src/VecSim/algorithms/brute_force/brute_force.cpp
  src/VecSim/algorithms/brute_force/brute_force.h
  src/VecSim/algorithms/brute_force/vector_block.cpp
  src/VecSim/algorithms/brute_force/vector_block.h
  tests/benchmark/bm_basics.cpp
  tests/unit/test_allocator.cpp
  tests/unit/test_bruteforce.cpp
  tests/unit/test_hnswlib.cpp
Labels: run-micro-benchmarks

#181 Improving pre-fetch logic - HNSW
  src/VecSim/algorithms/hnsw/hnsw_batch_iterator.cpp
  src/VecSim/algorithms/hnsw/hnswlib.h
Labels: run-micro-benchmarks

#211 Muliple branch based releases #3: 0.4 branch
  .github/release-drafter-config.yml
Labels: maintenance

#209 Muliple branch based releases #1: main branch
  .github/release-drafter-config.yml
Labels: maintenance

#212 Perf fix benchmarks run on tags
  .circleci/config.yml
Labels: maintenance

#214 Perf fix benchmarks run on tags [cherry-pick 0.3]
  .circleci/config.yml
Labels: maintenance

#215 Perf fix benchmarks run on tags [cherry-pick 0.4]
  .circleci/config.yml
Labels: maintenance

#213 Fp64_remove_SpaceInterface (#195)
  src/VecSim/algorithms/brute_force/brute_force.cpp
  src/VecSim/algorithms/brute_force/brute_force.h
  src/VecSim/algorithms/brute_force/vector_block.h
  src/VecSim/algorithms/hnsw/hnsw_batch_iterator.cpp
  src/VecSim/algorithms/hnsw/hnsw_batch_iterator.h
  src/VecSim/algorithms/hnsw/hnsw_wrapper.cpp
  src/VecSim/algorithms/hnsw/hnsw_wrapper.h
  src/VecSim/algorithms/hnsw/hnswlib.h
  src/VecSim/algorithms/hnsw/serialization.cpp
  src/VecSim/algorithms/hnsw/serialization.h
  src/VecSim/spaces/CMakeLists.txt
  src/VecSim/spaces/IP/IP.cpp
  src/VecSim/spaces/IP/IP.h
  src/VecSim/spaces/IP/IP_AVX.cpp
  src/VecSim/spaces/IP/IP_AVX.h
  src/VecSim/spaces/IP/IP_AVX512.cpp
  src/VecSim/spaces/IP/IP_AVX512.h
  src/VecSim/spaces/IP/IP_SSE.cpp
  src/VecSim/spaces/IP/IP_SSE.h
  src/VecSim/spaces/IP_space.cpp
  src/VecSim/spaces/IP_space.h
  src/VecSim/spaces/L2/L2.cpp
  src/VecSim/spaces/L2/L2.h
  src/VecSim/spaces/L2/L2_AVX.cpp
  src/VecSim/spaces/L2/L2_AVX.h
  src/VecSim/spaces/L2/L2_AVX512.cpp
  src/VecSim/spaces/L2/L2_AVX512.h
  src/VecSim/spaces/L2/L2_SSE.cpp
  src/VecSim/spaces/L2/L2_SSE.h
  src/VecSim/spaces/L2_space.cpp
  src/VecSim/spaces/L2_space.h
  src/VecSim/spaces/space_interface.h
  src/VecSim/spaces/spaces.cpp
  src/VecSim/spaces/spaces.h
  src/VecSim/utils/vec_utils.cpp
  src/VecSim/utils/vec_utils.h
  src/python_bindings/bindings.cpp
  tests/benchmark/bm_spaces.cpp
  tests/benchmark/bm_spaces_class.h
  tests/benchmark/bm_utils.cpp
  tests/unit/test_allocator.cpp
  tests/unit/test_hnswlib.cpp
  tests/unit/test_spaces.cpp
Labels: maintenance

#202 Fp64_add_datasize_to_vectorBlock
  src/VecSim/algorithms/brute_force/brute_force.cpp
  src/VecSim/algorithms/brute_force/brute_force.h
  src/VecSim/algorithms/brute_force/vector_block.cpp
  src/VecSim/algorithms/brute_force/vector_block.h
Labels: maintenance

#208 Changed distance function last argument type
  src/VecSim/algorithms/brute_force/brute_force.cpp
  src/VecSim/algorithms/brute_force/brute_force_single.cpp
  src/VecSim/algorithms/hnsw/hnsw_batch_iterator.cpp
  src/VecSim/algorithms/hnsw/hnswlib.h
  src/VecSim/spaces/IP/IP.cpp
  src/VecSim/spaces/IP/IP.h
  src/VecSim/spaces/IP/IP_AVX.cpp
  src/VecSim/spaces/IP/IP_AVX.h
  src/VecSim/spaces/IP/IP_AVX512.cpp
  src/VecSim/spaces/IP/IP_AVX512.h
  src/VecSim/spaces/IP/IP_SSE.cpp
  src/VecSim/spaces/IP/IP_SSE.h
  src/VecSim/spaces/L2/L2.cpp
  src/VecSim/spaces/L2/L2.h
  src/VecSim/spaces/L2/L2_AVX.cpp
  src/VecSim/spaces/L2/L2_AVX.h
  src/VecSim/spaces/L2/L2_AVX512.cpp
  src/VecSim/spaces/L2/L2_AVX512.h
  src/VecSim/spaces/L2/L2_SSE.cpp
  src/VecSim/spaces/L2/L2_SSE.h
  src/VecSim/spaces/spaces.h
  tests/benchmark/bm_spaces.cpp
  tests/unit/test_spaces.cpp
Labels: run-micro-benchmarks, maintenance

#204 Introducing multi-value indexing to FLAT algorithm
  src/CMakeLists.txt
  src/VecSim/algorithms/brute_force/brute_force.cpp
  src/VecSim/algorithms/brute_force/brute_force_multi.cpp
  src/VecSim/algorithms/brute_force/brute_force_multi.h
  tests/unit/CMakeLists.txt
  tests/unit/test_bruteforce.cpp
  tests/unit/test_bruteforce_multi.cpp
Labels: enhancement

#216 Index factory
  src/CMakeLists.txt
  src/VecSim/algorithms/brute_force/brute_force.cpp
  src/VecSim/algorithms/brute_force/brute_force.h
  src/VecSim/algorithms/brute_force/brute_force_factory.cpp
  src/VecSim/algorithms/brute_force/brute_force_factory.h
  src/VecSim/algorithms/hnsw/hnsw_factory.cpp
  src/VecSim/algorithms/hnsw/hnsw_factory.h
  src/VecSim/algorithms/hnsw/hnsw_wrapper.cpp
  src/VecSim/algorithms/hnsw/hnsw_wrapper.h
  src/VecSim/vec_sim.cpp
  tests/unit/test_allocator.cpp
Labels: maintenance

#220 Changed distance function last argument type (#208)
  src/VecSim/algorithms/brute_force/brute_force.cpp
  src/VecSim/algorithms/brute_force/brute_force_single.cpp
  src/VecSim/algorithms/hnsw/hnsw_batch_iterator.cpp
  src/VecSim/algorithms/hnsw/hnswlib.h
  src/VecSim/spaces/IP/IP.cpp
  src/VecSim/spaces/IP/IP.h
  src/VecSim/spaces/IP/IP_AVX.cpp
  src/VecSim/spaces/IP/IP_AVX.h
  src/VecSim/spaces/IP/IP_AVX512.cpp
  src/VecSim/spaces/IP/IP_AVX512.h
  src/VecSim/spaces/IP/IP_SSE.cpp
  src/VecSim/spaces/IP/IP_SSE.h
  src/VecSim/spaces/L2/L2.cpp
  src/VecSim/spaces/L2/L2.h
  src/VecSim/spaces/L2/L2_AVX.cpp
  src/VecSim/spaces/L2/L2_AVX.h
  src/VecSim/spaces/L2/L2_AVX512.cpp
  src/VecSim/spaces/L2/L2_AVX512.h
  src/VecSim/spaces/L2/L2_SSE.cpp
  src/VecSim/spaces/L2/L2_SSE.h
  src/VecSim/spaces/spaces.h
  tests/benchmark/bm_spaces.cpp
  tests/unit/test_spaces.cpp
Labels: maintenance

#221 Index factory (#216)
  src/CMakeLists.txt
  src/VecSim/algorithms/brute_force/brute_force.cpp
  src/VecSim/algorithms/brute_force/brute_force.h
  src/VecSim/algorithms/brute_force/brute_force_factory.cpp
  src/VecSim/algorithms/brute_force/brute_force_factory.h
  src/VecSim/algorithms/hnsw/hnsw_factory.cpp
  src/VecSim/algorithms/hnsw/hnsw_factory.h
  src/VecSim/algorithms/hnsw/hnsw_wrapper.cpp
  src/VecSim/algorithms/hnsw/hnsw_wrapper.h
  src/VecSim/vec_sim.cpp
  tests/unit/test_allocator.cpp
Labels: maintenance

#210 Muliple branch based releases #2: 0.3 branch
  .github/release-drafter-config.yml
Labels: maintenance
