Repository RedisAI/VectorSimilarity, pull requests merged in 2023-05, with the labels that each got.

#362 Call shrink to fit for id to label mapping in flat index
  src/VecSim/algorithms/brute_force/brute_force.h
  tests/unit/test_allocator.cpp
  tests/unit/test_bruteforce.cpp
Labels: multi-build, benchmarks-default

#365 shrink to fit in BF index [CP]
  src/VecSim/algorithms/brute_force/brute_force.h
  tests/unit/test_allocator.cpp
  tests/unit/test_bruteforce.cpp
Labels: multi-build

#361 Tiered index enable sync mode MOD-5106
  src/VecSim/algorithms/hnsw/hnsw.h
  src/VecSim/algorithms/hnsw/hnsw_tiered.h
  src/VecSim/algorithms/hnsw/hnsw_tiered_tests_friends.h
  src/VecSim/vec_sim.cpp
  src/VecSim/vec_sim.h
  src/VecSim/vec_sim_common.h
  src/VecSim/vec_sim_interface.cpp
  src/VecSim/vec_sim_interface.h
  src/VecSim/vec_sim_tiered_index.h
  tests/unit/test_hnsw_tiered.cpp
Labels: multi-build

#360 Implement `rangeQuery` for VecSimTieredIndex - [MOD-5164]
  src/VecSim/algorithms/hnsw/hnsw.h
  src/VecSim/algorithms/hnsw/hnsw_tiered.h
  src/VecSim/algorithms/hnsw/hnsw_tiered_tests_friends.h
  src/VecSim/utils/query_result_utils.h
  src/VecSim/utils/vec_utils.cpp
  src/VecSim/utils/vec_utils.h
  src/VecSim/vec_sim.cpp
  src/VecSim/vec_sim_index.h
  src/VecSim/vec_sim_interface.h
  src/VecSim/vec_sim_tiered_index.h
  tests/unit/test_hnsw_tiered.cpp
  tests/unit/test_utils.cpp
Labels: multi-build, benchmarks-default

#367 idToLabel in flat index - shrink to fit and avoid invalid access MOD-5212
  src/VecSim/algorithms/brute_force/brute_force.h
  src/VecSim/algorithms/brute_force/brute_force_multi.h
  src/VecSim/algorithms/brute_force/brute_force_single.h
  src/VecSim/algorithms/hnsw/hnsw_tiered.h
  tests/unit/test_allocator.cpp
  tests/unit/test_bruteforce.cpp
  tests/unit/test_hnsw_tiered.cpp
Labels: multi-build

#368 Tiered HNSW - `preferAdHocSearch` fix
  src/VecSim/algorithms/brute_force/brute_force.h
  src/VecSim/algorithms/hnsw/hnsw.h
  src/VecSim/algorithms/hnsw/hnsw_tiered.h
  src/VecSim/algorithms/hnsw/hnsw_tiered_tests_friends.h
  src/VecSim/vec_sim_tiered_index.h
  tests/unit/test_bruteforce.cpp
  tests/unit/test_hnsw.cpp
  tests/unit/test_hnsw_multi.cpp
  tests/unit/test_hnsw_tiered.cpp
Labels: multi-build

#363 Tiered index info MOD-4315
  src/VecSim/algorithms/brute_force/brute_force.h
  src/VecSim/algorithms/hnsw/hnsw.h
  src/VecSim/algorithms/hnsw/hnsw_tiered.h
  src/VecSim/algorithms/hnsw/hnsw_tiered_tests_friends.h
  src/VecSim/index_factories/tiered_factory.cpp
  src/VecSim/info_iterator.h
  src/VecSim/info_iterator_struct.h
  src/VecSim/memory/vecsim_base.h
  src/VecSim/utils/vec_utils.cpp
  src/VecSim/utils/vec_utils.h
  src/VecSim/vec_sim_common.h
  src/VecSim/vec_sim_index.h
  src/VecSim/vec_sim_tiered_index.h
  src/python_bindings/bindings.cpp
  tests/benchmark/bm_batch_iterator.h
  tests/benchmark/bm_common.h
  tests/module/memory_test.c
  tests/unit/test_allocator.cpp
  tests/unit/test_bruteforce.cpp
  tests/unit/test_bruteforce_multi.cpp
  tests/unit/test_hnsw.cpp
  tests/unit/test_hnsw_multi.cpp
  tests/unit/test_hnsw_parallel.cpp
  tests/unit/test_hnsw_tiered.cpp
  tests/unit/test_utils.cpp
  tests/unit/test_utils.h
Labels: multi-build

#372 Poetry only build (#369) 0.7
  Makefile
  pyproject.toml
  requirements.txt
  tox.ini
Labels: multi-build

#371 Poetry only build (#369) - cp 0.6
  Makefile
  pyproject.toml
  requirements.txt
  tox.ini
Labels: multi-build

#364 Tiered HNSW - API update - [MOD-5099]
  src/VecSim/algorithms/brute_force/brute_force.h
  src/VecSim/algorithms/brute_force/brute_force_multi.h
  src/VecSim/algorithms/brute_force/brute_force_single.h
  src/VecSim/algorithms/hnsw/hnsw.h
  src/VecSim/algorithms/hnsw/hnsw_tiered.h
  src/VecSim/memory/vecsim_base.h
  src/VecSim/memory/vecsim_malloc.cpp
  src/VecSim/memory/vecsim_malloc.h
  src/VecSim/vec_sim.cpp
  src/VecSim/vec_sim.h
  src/VecSim/vec_sim_common.h
  src/VecSim/vec_sim_index.h
  src/VecSim/vec_sim_interface.h
  src/VecSim/vec_sim_tiered_index.h
  tests/benchmark/bm_vecsim_basics.h
  tests/unit/test_allocator.cpp
  tests/unit/test_bruteforce.cpp
  tests/unit/test_bruteforce_multi.cpp
  tests/unit/test_hnsw.cpp
  tests/unit/test_hnsw_multi.cpp
  tests/unit/test_hnsw_tiered.cpp
  tests/unit/test_utils.cpp
  tests/unit/test_utils.h
Labels: multi-build

#373 Small fixes due to CI failures
  src/VecSim/vec_sim_common.h
  tests/unit/test_bruteforce.cpp
  tests/unit/test_bruteforce_multi.cpp
  tests/unit/test_hnsw.cpp
  tests/unit/test_hnsw_multi.cpp
Labels: multi-build

#378 optimize swap jobs handling
  src/VecSim/algorithms/hnsw/hnsw_tiered.h
Labels: multi-build

#379 disable fp64 index unit tests by default
  Makefile
  tests/unit/CMakeLists.txt
  tests/unit/test_utils.h
Labels: multi-build

#381 sync info
  src/VecSim/vec_sim_tiered_index.h
Labels: multi-build

#355 Tiered index flow tests - MOD-4324
  src/VecSim/vec_sim_tiered_index.h
  src/python_bindings/bindings.cpp
  src/python_bindings/tiered_index_mock.h
  tests/flow/common.py
  tests/flow/test_hnsw_tiered.py
Labels: multi-build

#384 larger arm machine
  .github/workflows/arm.yml
Labels: arm

#385 remove fp64 from tiered index tests
  tests/unit/test_utils.h
Labels: multi-build

#386 rocky 8.8
  .install/rocky_linux_8.8.sh
Labels: multi-build
