Repository RedisAI/VectorSimilarity, pull requests merged in 2024-12, with the labels that each got.

#556 Disable old OSs + add manual trigger to merge queue and nightly flows
  .github/workflows/event-merge-to-queue.yml
  .github/workflows/event-nightly.yml
Labels: backport 0.6, backport 0.7, backport 0.8

#562 format according to ubuntu24
  src/VecSim/algorithms/hnsw/graph_data.h
  src/python_bindings/bindings.cpp
  tests/module/redismodule.h
  tests/unit/test_hnsw_parallel.cpp
Labels: backport 0.6, backport 0.7, backport 0.8

#567 [MOD-8244] fix TieredFactory::EstimateInitialSize
  src/VecSim/index_factories/brute_force_factory.cpp
  src/VecSim/index_factories/brute_force_factory.h
  src/VecSim/index_factories/components/components_factory.h
  src/VecSim/index_factories/components/preprocessors_factory.h
  src/VecSim/index_factories/hnsw_factory.cpp
  src/VecSim/index_factories/hnsw_factory.h
  src/VecSim/index_factories/tiered_factory.cpp
  src/VecSim/spaces/computer/preprocessor_container.h
  src/VecSim/vec_sim_index.h
  tests/unit/test_hnsw_tiered.cpp
Labels: backport 8.0

#560 [MOD-8198] Introduce INT8 distance functions
  cmake/x86_64InstructionFlags.cmake
  src/VecSim/spaces/CMakeLists.txt
  src/VecSim/spaces/IP/IP.cpp
  src/VecSim/spaces/IP/IP.h
  src/VecSim/spaces/IP/IP_AVX512F_BW_VL_VNNI_INT8.h
  src/VecSim/spaces/IP_space.cpp
  src/VecSim/spaces/IP_space.h
  src/VecSim/spaces/L2/L2.cpp
  src/VecSim/spaces/L2/L2.h
  src/VecSim/spaces/L2/L2_AVX512F_BW_VL_VNNI_INT8.h
  src/VecSim/spaces/L2_space.cpp
  src/VecSim/spaces/L2_space.h
  src/VecSim/spaces/computer/calculator.h
  src/VecSim/spaces/functions/AVX512F_BW_VL_VNNI.cpp
  src/VecSim/spaces/functions/AVX512F_BW_VL_VNNI.h
  src/VecSim/spaces/functions/implementation_chooser.h
  src/VecSim/spaces/spaces.cpp
  tests/benchmark/CMakeLists.txt
  tests/benchmark/benchmarks.sh
  tests/benchmark/spaces_benchmarks/bm_spaces.h
  tests/benchmark/spaces_benchmarks/bm_spaces_bf16.cpp
  tests/benchmark/spaces_benchmarks/bm_spaces_fp16.cpp
  tests/benchmark/spaces_benchmarks/bm_spaces_fp32.cpp
  tests/benchmark/spaces_benchmarks/bm_spaces_fp64.cpp
  tests/benchmark/spaces_benchmarks/bm_spaces_int8.cpp
  tests/unit/CMakeLists.txt
  tests/unit/test_allocator.cpp
  tests/unit/test_bf16.cpp
  tests/unit/test_bruteforce.cpp
  tests/unit/test_bruteforce_multi.cpp
  tests/unit/test_common.cpp
  tests/unit/test_fp16.cpp
  tests/unit/test_hnsw.cpp
  tests/unit/test_hnsw_multi.cpp
  tests/unit/test_hnsw_parallel.cpp
  tests/unit/test_hnsw_tiered.cpp
  tests/unit/test_spaces.cpp
  tests/unit/unit_test_utils.cpp
  tests/unit/unit_test_utils.h
  tests/utils/tests_utils.h
Labels: bm-spaces, backport 8.0

#523 Raw vectors data layer in HNSW + move to base class [MOD-7496]
  src/VecSim/algorithms/brute_force/brute_force.h
  src/VecSim/algorithms/hnsw/hnsw.h
  src/VecSim/algorithms/hnsw/hnsw_serializer.h
  src/VecSim/containers/data_blocks_container.cpp
  src/VecSim/containers/data_blocks_container.h
  src/VecSim/containers/raw_data_container_interface.h
  src/VecSim/index_factories/hnsw_factory.cpp
  src/VecSim/utils/serializer.cpp
  src/VecSim/utils/serializer.h
  src/VecSim/vec_sim_index.h
  tests/unit/data/1k-d4-L2-M8-ef_c10_FLOAT32_multi_100labels.v3
  tests/unit/data/1k-d4-L2-M8-ef_c10_FLOAT32_single.v3
  tests/unit/test_allocator.cpp
  tests/unit/test_hnsw.cpp
  tests/unit/test_hnsw_tiered.cpp
Labels: benchmarks-default, backport 8.0

#566 [MOD-8200] [MOD-8202] INT8 index
  src/VecSim/algorithms/hnsw/hnsw_tiered_tests_friends.h
  src/VecSim/index_factories/brute_force_factory.cpp
  src/VecSim/index_factories/components/components_factory.h
  src/VecSim/index_factories/hnsw_factory.cpp
  src/VecSim/index_factories/tiered_factory.cpp
  src/VecSim/spaces/IP/IP_AVX512F_BW_VL_VNNI_INT8.h
  src/VecSim/spaces/normalize/compute_norm.h
  src/VecSim/spaces/normalize/normalize_naive.h
  src/VecSim/spaces/spaces.cpp
  src/VecSim/utils/vec_utils.cpp
  src/VecSim/utils/vec_utils.h
  src/VecSim/vec_sim.cpp
  src/VecSim/vec_sim_common.h
  src/VecSim/vec_sim_debug.cpp
  src/VecSim/vec_sim_index.h
  src/python_bindings/bindings.cpp
  tests/benchmark/spaces_benchmarks/bm_spaces_int8.cpp
  tests/unit/CMakeLists.txt
  tests/unit/test_common.cpp
  tests/unit/test_components.cpp
  tests/unit/test_hnsw_tiered.cpp
  tests/unit/test_int8.cpp
  tests/unit/test_spaces.cpp
  tests/unit/unit_test_utils.cpp
  tests/unit/unit_test_utils.h
  tests/utils/tests_utils.h
Labels: backport 8.0

#576 Improve HNSW-parallel tests - [MOD-7970]
  tests/unit/test_hnsw_parallel.cpp
Labels: backport 0.7, backport 0.8, backport 8.0

#578 initialize dataSize ion abstractInitParams in tiered factory NewIndex from hnsw file
  src/VecSim/index_factories/tiered_factory.h
Labels: bm-basics-fp32-single, backport 8.0

#585 Flow test improvements
  pyproject.toml
  tests/flow/test_hnsw_parallel.py
Labels: backport 0.7, backport 0.8, backport 8.0
