Repository RedisAI/VectorSimilarity, pull requests merged in 2024-07, with the labels that each got.

#480 Remove cetnos7
  .github/workflows/centos7.yml
  .github/workflows/event-merge-to-queue.yml
  .github/workflows/event-nightly.yml
  .install/centos_linux_7.sh
Labels: backport 0.8

#479 [MOD-7325] Re-design benchmark class:
  tests/benchmark/spaces_benchmarks/bm_spaces.h
  tests/benchmark/spaces_benchmarks/bm_spaces_bf16.cpp
  tests/benchmark/spaces_benchmarks/bm_spaces_class.h
  tests/benchmark/spaces_benchmarks/bm_spaces_fp16.cpp
  tests/benchmark/spaces_benchmarks/bm_spaces_fp32.cpp
  tests/benchmark/spaces_benchmarks/bm_spaces_fp64.cpp
Labels: bm-spaces, backport 0.8

#481 [MOD-7048] - Distance claculations - Add constexpr and use fmadd
  src/VecSim/spaces/IP/IP_AVX2_BF16.h
  src/VecSim/spaces/IP/IP_AVX512_FP16.h
  src/VecSim/spaces/IP/IP_AVX512_FP32.h
  src/VecSim/spaces/IP/IP_AVX512_FP64.h
  src/VecSim/spaces/IP/IP_AVX_FP32.h
  src/VecSim/spaces/IP/IP_AVX_FP64.h
  src/VecSim/spaces/IP/IP_F16C_FP16.h
  src/VecSim/spaces/IP/IP_SSE_FP32.h
  src/VecSim/spaces/IP/IP_SSE_FP64.h
  src/VecSim/spaces/L2/L2_AVX2_BF16.h
  src/VecSim/spaces/L2/L2_AVX512_FP16.h
  src/VecSim/spaces/L2/L2_AVX512_FP32.h
  src/VecSim/spaces/L2/L2_AVX512_FP64.h
  src/VecSim/spaces/L2/L2_AVX_FP32.h
  src/VecSim/spaces/L2/L2_AVX_FP64.h
  src/VecSim/spaces/L2/L2_F16C_FP16.h
  src/VecSim/spaces/L2/L2_SSE_FP64.h
Labels: backport 0.7, backport 0.8

#477 [MOD - 6778] AVX512_FP16 distance functions
  .github/workflows/flow-temp.yml
  .install/rocky_linux_8.sh
  .install/rocky_linux_9.sh
  .install/ubuntu_20.04.sh
  .install/ubuntu_22.04.sh
  cmake/x86_64InstructionFlags.cmake
  src/VecSim/spaces/CMakeLists.txt
  src/VecSim/spaces/IP/IP_AVX512FP16_FP16.h
  src/VecSim/spaces/IP/IP_AVX512F_FP16.h
  src/VecSim/spaces/IP/IP_AVX512F_FP32.h
  src/VecSim/spaces/IP/IP_AVX512F_FP64.h
  src/VecSim/spaces/IP/IP_SSE3_BF16.h
  src/VecSim/spaces/IP_space.cpp
  src/VecSim/spaces/L2/L2_AVX512FP16_FP16.h
  src/VecSim/spaces/L2/L2_AVX512F_FP16.h
  src/VecSim/spaces/L2/L2_AVX512F_FP32.h
  src/VecSim/spaces/L2/L2_AVX512F_FP64.h
  src/VecSim/spaces/L2/L2_SSE3_BF16.h
  src/VecSim/spaces/L2/L2_SSE_FP32.h
  src/VecSim/spaces/L2_space.cpp
  src/VecSim/spaces/functions/AVX512.h
  src/VecSim/spaces/functions/AVX512F.cpp
  src/VecSim/spaces/functions/AVX512F.h
  src/VecSim/spaces/functions/AVX512FP16.cpp
  src/VecSim/spaces/functions/AVX512FP16.h
  src/VecSim/types/bfloat16.h
  src/VecSim/types/float16.h
  tests/benchmark/spaces_benchmarks/bm_spaces.h
  tests/benchmark/spaces_benchmarks/bm_spaces_class.h
  tests/benchmark/spaces_benchmarks/bm_spaces_fp16.cpp
  tests/benchmark/spaces_benchmarks/bm_spaces_fp32.cpp
  tests/benchmark/spaces_benchmarks/bm_spaces_fp64.cpp
  tests/unit/CMakeLists.txt
  tests/unit/test_fp16.cpp
  tests/unit/test_spaces.cpp
  tests/unit/test_types.cpp
Labels: bm-spaces, backport 0.8, bm-basics-fp16-single

#488 GHA - update action versions
  .github/workflows/event-pull_request.yml
  .github/workflows/release-drafter.yml
  .github/workflows/task-check-docs.yml
Labels: backport 0.6, backport 0.7, backport 0.8

#486 Enhance bm files download and add dispatcher to bm flow
  .github/workflows/benchmark.yml
  tests/benchmark/bm_files.sh
  tests/benchmark/data/serializer.py
Labels: bm-basics-fp32-single, backport 0.8

#495 exit if bm_files.sh input is not one of the expected inputs
  tests/benchmark/bm_files.sh
Labels: bm-spaces, backport 0.6, backport 0.7, backport 0.8

#499 Add bionic to PR validation on merge-to-queue
  .github/workflows/event-merge-to-queue.yml
Labels: backport 0.8

#494 fix flow tests
  .github/workflows/event-pull_request.yml
  .github/workflows/flow-temp.yml
  Makefile
  pyproject.toml
  src/python_bindings/CMakeLists.txt
  tests/flow/common.py
Labels: backport 0.8

#502 [MOD-7049] Change bm dimensions
  .install/ubuntu_20.04.sh
  .install/ubuntu_22.04.sh
  tests/benchmark/spaces_benchmarks/bm_spaces.h
Labels: bm-spaces, backport 0.8

#506 Parallel upload bm results to grafana
  .github/workflows/benchmark.yml
Labels: bm-basics-bf16-single

#505 [MOD-7297] Replace Variable Length Array on stack with heap allocation
  .github/workflows/flow-temp.yml
  src/VecSim/algorithms/hnsw/hnsw.h
  src/VecSim/algorithms/hnsw/hnsw_serializer.h
  src/VecSim/algorithms/hnsw/hnsw_tiered.h
  src/VecSim/memory/vecsim_malloc.cpp
  src/VecSim/memory/vecsim_malloc.h
  src/VecSim/spaces/normalize/normalize_naive.h
  src/VecSim/vec_sim_index.h
  src/VecSim/vec_sim_tiered_index.h
Labels: benchmarks-all, backport 0.8

#478 Refactor + maintain node's in-degree field in HNSW
  src/VecSim/algorithms/hnsw/graph_data.h
  src/VecSim/algorithms/hnsw/hnsw.h
  src/VecSim/algorithms/hnsw/hnsw_batch_iterator.h
  src/VecSim/algorithms/hnsw/hnsw_serializer.h
  src/VecSim/algorithms/hnsw/hnsw_serializer_declarations.h
  src/VecSim/index_factories/hnsw_factory.cpp
  src/VecSim/utils/serializer.cpp
  src/VecSim/utils/serializer.h
  src/VecSim/utils/vec_utils.h
  src/VecSim/utils/vecsim_stl.h
  tests/unit/data/1k-d4-L2-M8-ef_c10_FLOAT32_multi_100labels_.hnsw_v3
  tests/unit/data/1k-d4-L2-M8-ef_c10_FLOAT32_single.hnsw_v3
  tests/unit/test_allocator.cpp
  tests/unit/test_bf16.cpp
  tests/unit/test_fp16.cpp
  tests/unit/test_hnsw.cpp
  tests/unit/test_hnsw_multi.cpp
  tests/unit/test_hnsw_parallel.cpp
  tests/unit/test_hnsw_tiered.cpp
Labels: benchmarks-default
