Repository RedisAI/VectorSimilarity, pull requests merged in 2025-07, with the labels that each got.

#703 Generalize Micro-benchmarks [MOD-10160]
  tests/benchmark/bm_batch_iterator.h
  tests/benchmark/bm_common.h
  tests/benchmark/bm_definitions.h
  tests/benchmark/bm_initialization/bm_basics_initialize_bf16.h
  tests/benchmark/bm_initialization/bm_basics_initialize_fp16.h
  tests/benchmark/bm_initialization/bm_basics_initialize_fp32.h
  tests/benchmark/bm_initialization/bm_basics_initialize_fp64.h
  tests/benchmark/bm_initialization/bm_basics_initialize_int8.h
  tests/benchmark/bm_initialization/bm_basics_initialize_uint8.h
  tests/benchmark/bm_initialization/bm_updated_initialize_fp32.h
  tests/benchmark/bm_updated_index.h
  tests/benchmark/bm_vecsim_basics.h
  tests/benchmark/bm_vecsim_general.cpp
  tests/benchmark/bm_vecsim_general.h
  tests/benchmark/bm_vecsim_index.h
  tests/benchmark/run_files/bm_basics_multi_bf16.cpp
  tests/benchmark/run_files/bm_basics_multi_fp16.cpp
  tests/benchmark/run_files/bm_basics_multi_fp32.cpp
  tests/benchmark/run_files/bm_basics_multi_fp64.cpp
  tests/benchmark/run_files/bm_basics_multi_int8.cpp
  tests/benchmark/run_files/bm_basics_multi_uint8.cpp
  tests/benchmark/run_files/bm_basics_single_bf16.cpp
  tests/benchmark/run_files/bm_basics_single_fp16.cpp
  tests/benchmark/run_files/bm_basics_single_fp32.cpp
  tests/benchmark/run_files/bm_basics_single_fp64.cpp
  tests/benchmark/run_files/bm_basics_single_int8.cpp
  tests/benchmark/run_files/bm_basics_single_uint8.cpp
  tests/benchmark/run_files/bm_batch_iterator_multi_bf16.cpp
  tests/benchmark/run_files/bm_batch_iterator_multi_fp16.cpp
  tests/benchmark/run_files/bm_batch_iterator_multi_fp32.cpp
  tests/benchmark/run_files/bm_batch_iterator_multi_fp64.cpp
  tests/benchmark/run_files/bm_batch_iterator_multi_int8.cpp
  tests/benchmark/run_files/bm_batch_iterator_multi_uint8.cpp
  tests/benchmark/run_files/bm_batch_iterator_single_bf16.cpp
  tests/benchmark/run_files/bm_batch_iterator_single_fp16.cpp
  tests/benchmark/run_files/bm_batch_iterator_single_fp32.cpp
  tests/benchmark/run_files/bm_batch_iterator_single_fp64.cpp
  tests/benchmark/run_files/bm_batch_iterator_single_int8.cpp
  tests/benchmark/run_files/bm_batch_iterator_single_uint8.cpp
  tests/benchmark/run_files/bm_updated_index_single_fp32.cpp
Labels: bm-basics-fp16-single

#720 [SVS] Add support for GLIBC 2.26 systems and GCC v11.2. E.g. AmazonLinux 2
  cmake/svs.cmake
  tests/unit/test_svs.cpp
Labels: backport 8.2

#722 [CI] Fix nightly
  .github/workflows/benchmark.yml
  .gitignore
Labels: benchmarks-default

#731 Use SVS RC2 binaries
  cmake/svs.cmake
Labels: backport 8.2

#733 [SVS] Fix SVSTieredIndexTestBasic.overwriteVectorAsync test
  src/VecSim/algorithms/svs/svs_tiered.h
  tests/unit/test_svs_tiered.cpp
Labels: backport 8.2
